server:
  port: 8080



spring:
  datasource:
    username: root
    password: 123456
    #?serverTimezone=UTC???????
    url: jdbc:mysql://localhost:3306/springboot?serverTimezone=UTC&useUnicode=true&characterEncoding=utf-8
    driver-class-name: com.mysql.cj.jdbc.Driver



  thymeleaf:
    encoding:  UTF-8
    cache:  false
    mode:  HTML

mybatis:
  type-aliases-package: com.wangyuhang.pojo
  mapper-locations: classpath:mybatis/mapper/*.xml


